### ISSUE TITLE
como usuario me gustaria visitar una pagina amigable

### ISSUE THREAD

**Issue by dalirod** [Johndbm/Travel-Med#22]
El usuairo necesita un homepage con una propuesta de los servicios que ofrecemos...

 

- [x] Crearemos una "vista" home con "componentes":

 

- [x] Navbar con un boton (de inicio de sesion)

- [x] Creacion del logo

 

- [x] Carrusel con especialistas

 

- [x] Sobre nosotros

 

- [x] Galeria con imagenes

- [x] Footer

**Comment by Johndbm** [comment]
- [x] Eliminar a Rigo del homepage, please 🙏🏽
